### ISSUE TITLE
Implement C# client library for meXBT exchange

### ISSUE THREAD

**Issue by williamcoates** [meXBT/mexbt-c-sharp#1]
The library should allow developers to access the api functions listed below (check the ruby client for code examples and links to documentation https://github.com/meXBT/mexbt-ruby). Obviously stick to idiomatic naming conventions for the programming language used, and feel free to change function names if you can find more idiomatic or logical alternatives. 

Make sure the private api optionally supports connecting to the sandbox.

It should be possible to use the public api functions without authenticating.

Public API

ticker
order_book
trades
trades_by_date

(all of these should allow choosing market, which can currently be one of btcmxn or btcusd)

Private API

create_order
modify_order
cancel_order
cancel_all_orders
balance
trades
orders
deposit_address(currency) 
withdraw
info

**Comment by ahimta** [comment]
Most functions seem to work except for:
- orders/create: responds with a "rejectReason" of "Verification level failed".
- withdraw: responds with HTTP status 200, but empty content body as opposed to the specified behavior in Apiary docs.

You can find my implementation here: https://github.com/Ahimta/mexbt-c-sharp

**Comment by williamcoates** [comment]
There seems to be an issue with order creation on sandbox, I am investigating. The withdraw problem I believe is that the amount has to be a string, very confusingly (this is due to the underlying api we are using unfortunately).

Please create a pull request when ready, ill get back to you on the order issue

**Comment by williamcoates** [comment]
So on the sandbox, if you go through verification ironically then you can't make orders. A fresh account with verificationLevel at zero will work though.

I can also set your level to zero if you tell me your registered email (you can email it to me)

**Comment by ahimta** [comment]
I created another account and order endpoints now work.

However, withdraw still fails with rejectReason "No withdraw processor is registered for this class".
In addition the withdraw amount is now formatted as specified in the [mexbt-php pull request](https://github.com/meXBT/mexbt-php/pull/2) (6 decimal places when in sandbox mode and 8 in production).

You can find my pull request here: https://github.com/meXBT/mexbt-c-sharp/pull/2

**Comment by williamcoates** [comment]
Withdraw requests don't function on the sandbox unfortunately, so I think that is the issue.
